### ISSUE TITLE
Headings for Lesson Navigation

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/javascript_curriculum#102]
The lesson navigation feature will use headings that are common to most lessons, these are as follows:

* Introduction
* Learning Outcomes
* Assignment
* Additional Resources

Each of these headings need to be h3's

I'm aware that a lot of the lessons in the JS course do not currently have these sections. But we should put the headings in for the sections that do exist in the lessons currently. For example most lessons will have an Introduction and an Assignment.

**Comment by JonathanYiv** [comment]
I skimmed through all the files and they all seem to use h3s, with occasional h4s for subsections

**Comment by KevinMulhern** [comment]
Yeah I did this on Friday, sorry I forgot to close this 😄
