### ISSUE TITLE
Add a Link to File on Github on Projects

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/javascript_curriculum#105]
On chat we've seen some students confused about what repo they should submit thier solution to for a project.

A quick and easy solution to this problem we have done on the ruby course is to add this kind of line below the "Student Solutions" heading:

```
Submit a link below to this [file](https://github.com/TheOdinProject/ruby_course/blob/master/ruby_programming/basic_ruby/advanced_building_blocks_project.md) on the ruby course github repo with your files in it by using a pull request.  See the section on [Contributing](http://github.com/TheOdinProject/curriculum/blob/master/contributing.md) for how.
```

**Comment by Mycroft1891** [comment]
Perfect, I suggested the same thing inside the `web development 101` repo because some solution go into the `javascript` repo while others got into the `curriculum` repo.

**Comment by codyloyd** [comment]
👍 yep
lets do it

**Comment by mindovermiles262** [comment]
Is there somehow we can implement this using the seeds.rb.  `link_to 'github repo' if lesson.project?`

**Comment by KevinMulhern** [comment]
Not on the markdown file itself. It would have to be on the lesson show view. So either above or below the lesson content. From a user experience perspective I don't think its the right way to go, the instructions would be too far away from the section where they would be relevant imo.

**Comment by Mycroft1891** [comment]
I think we should add it right above the student's solution list. It would make sense there IMO:
like here: https://www.theodinproject.com/courses/ruby-programming/lessons/oop?ref=lnav

**Comment by JonathanYiv** [comment]
I will do it

**Comment by 105ron** [comment]
How is progress going on this?

**Comment by heyalvaro** [comment]
Just reviewed the Javascript section of the course and this is still missing. I cloned the curriculum repo and searched for all the pages containing "Submit a link". Will add a link to their corresponding solution .md file to have them standarized

**Comment by heyalvaro** [comment]
@KevinMulhern Can I have this issue assigned?

**Comment by KevinMulhern** [comment]
Hi @Mycroft1891, its all yours 😄

**Comment by heyalvaro** [comment]
@KevinMulhern @Mycroft1891 I've started working on this. Already fixed the html_css part of the course and the javascript part of the course. Here's a google docs spreadsheet to keep track. https://docs.google.com/spreadsheets/d/1OUQQkfoio2ooyrmoXxO5yhUgI8hQ6Yfn1I1Dj_YKv7M/edit?usp=sharing

The only remaining question is, should the text after the Student Solutions header be standardized?

**Comment by JonathanYiv** [comment]
Bleh, I completely forgot about this. I'm sorry
