### ISSUE TITLE
JS101 - points to ponder

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/javascript_curriculum#17]
This issue entails going through the lessons in the JS101 course, reading or skimming through the resources and populating the "points to ponder" section of each lesson. 

The idea behind this section of the lesson is to give students a chance to self-reflect on the things they've learned and make sure they've picked up everything they need from the materials.   Here's an example of the format from the "Fundamentals 1" lesson:

### Points to Ponder

> Use this section to quiz yourself.  If you know all these answers then you can comfortably skip, or at least skim through this lesson.  After the lesson, come on back here and read these again to make sure you haven't missed anything crucial.

* What are the 7 basic types in Javascript?
* What is a variable, and how do you declare one in Javascript?
* Can you name all 3 ways to declare a variable in Javascript and when would you want to use each one?

**Comment by mindovermiles262** [comment]
May also be helpful to add drop downs with solutions

See [this gist](https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61) for how-to
