### ISSUE TITLE
Final JS101 projects

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/javascript_curriculum#19]
The project is already decided, just need to write the lesson.

2 projects => 
on screen calculator
more JS test-first exercises

**Comment by colevandersWands** [comment]
https://github.com/jankeLearning/projects/tree/master/cleancalc
could think about using the first 3 steps of this project.

learning objectives:
- build a calc from specs
- procedural to oop (steps 0 -> 1)
- logic is separate from framework (1, 2)
    - in 1 you build a terminal interface
    - in 2 you build an html/js interface
- in all steps you use the same exact calc object.
- also an opportunity to write a testing suite
- and to have a lesson on specs and code portability
    - if done right, anyone can replace their calc object with another person's and their code will still work
- objects - needs to use 'this'

**Comment by colevandersWands** [comment]
https://github.com/galvazudys/cleancalc 
https://galvazudys.github.io/cleancalc/

one of our student's finished clean-calfs

comes with a completely navigable repo
- readme
- versions
- demo
- tests

**Comment by codyloyd** [comment]
yep.. that's exactly what I was thinking of doing @colevandersWands

**Comment by colevandersWands** [comment]
we have content to support all of those learning objectives.  would you like to make a tidy folder of it all for you?

**Comment by codyloyd** [comment]
I think we're good for now.
