### ISSUE TITLE
OOP (Prototypal inheritance) lesson

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/javascript_curriculum#20]
Discuss Object Oriented Programming in JavaScript

JS DOES NOT HAVE CLASSES. This section is important.. crucial even because students will may be coming from Ruby or Java or any other language that handles inheritance differently

Prototypal Inheritance:
What/How
WHY.
Prototypes vs. Classes

Projects may include anything.. will have to brainstorm on that... some sort of game like connect-four or battleship. Maybe tictactoe if we haven't hit it yet.

**Comment by colevandersWands** [comment]
Here's a possibility for the oop lessons.  for now i'm linking them, it seems easier for now than flooding this file or creating extras:  
  
* using single objects   
  - https://github.com/jankeLearning/content-md/blob/master/programming-and-paradigms/02-oop-single-objects.md   
* prototypes  
  - https://github.com/jankeLearning/content-md/blob/master/programming-and-paradigms/03-prototypes.md
* factories  
  - https://github.com/jankeLearning/content-md/blob/master/programming-and-paradigms/03-factories.md   
* classical patterns  
  - https://github.com/jankeLearning/content-md/blob/master/programming-and-paradigms/03-classes.md  
* advanced patterns  
  - this one is in progress  
* fp vs oop  
  - in progress, nearly done.  especially important for people with experience in ruby. To sum this one up - oop and fp refer to the 'basic units' of your program, are they functions or objects?  do you use data bundled with functionality (oop), or functions bundled with data (fp).  This is tricky in JS, it's 'good' to use single simple objects as the bricks of your app but to treat the whole app like a funcitonal programming - objects behave something like pure functions from the outside's perspective, and immutabe data flow.  OOPing in JS is a totally differnt game

**Comment by colevandersWands** [comment]
This is what was in that conflictly pull request

**Comment by codyloyd** [comment]
cool.. I'll dig through the resources a little more later. 💯
