### ISSUE TITLE
es6 lesson

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/javascript_curriculum#22]
I am hoping that we will not have to cover too much here.. Presumably many of the syntax things and features will be covered in earlier lessons.. however there are a few little details that need covered, including a section on transpilers. things to cover include:

Babel! (maybe we should write our own.. but this tutorial is pretty hip https://github.com/verekia/js-stack-from-scratch)
Destructuring
Arrow Functions
??? probably something else I'm forgetting

Probably don't need projects here.. students can just start working this stuff into their current work. Might suggest students go back to a previous project and look for ways they could use these techniques

**Comment by colevandersWands** [comment]
For this I've found a paragraph or two explaining ecmascript, talking about how browsers are annoying, and saying that javascript is getting super cool is enough if it's accompanied by some links that explain the most useful features of es6. 
For the tans piling, you can just link to the webpack/build project.  This lesson could be a very good lesson to put right before that project

would you like me to do this?

**Comment by codyloyd** [comment]
you can do this.. sure.
You should mention Babel and manually transpiling using their CLI.. Might also show a demonstration using their repl: https://babeljs.io/repl/ and then just say "we'll show you how to automate all this in the next lesson"
