### ISSUE TITLE
JavaScript Testing

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/javascript_curriculum#25]
Students will have had exposure to TDD by doing our JS exercises, so they should already have some idea of the process although they will not have written any of their own tests at this point.

This lesson should reiterate the importance/usefulness of TDD in general and then discuss the syntax for writing tests.  We're using Jasmine, though it might be useful to at least mention the other big frameworks (Mocha, Chai, Jest) . They all do more or less the same thing with very similar syntax even.

Should have a relatively simple project where students are encouraged to TDD their code.

**Comment by colevandersWands** [comment]
https://github.com/colevandersWands/javascript_curriculum/blob/morejs-testing/MoreJS/testing.md

It's late, i'll figure out how to fix the pull requests in a bit.  Guess I still gotta practice this
In the meantime you can take a look through what i made and maybe even just copy paste
