### ISSUE TITLE
webpack

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/javascript_curriculum#26]
We don't need to go TOOO far into this... but once we start really digging into OOP and Babel and other things it will be useful to know how to compile/transpile your code so you can write with multiple files and use new features in older browsers etc.

Also, just about all the front end frameworks use webpack to run these days, so this will be important prereq for that stuff if we ever get there.

**Comment by iansowinski** [comment]
[this](https://github.com/verekia/js-stack-from-scratch) was extreamly helpful for me

**Comment by colevandersWands** [comment]
Building and compiling markdown
    https://github.com/jankeLearning/content-md/blob/master/dev-knowledge/04-packaging.md
Project
    https://github.com/jankeLearning/projects/tree/master/04-be-you-tube

it's gulp and babel, not web pack.  but the principle is close enoug, difference tools.  It's a got a pretty understandable gulp file

**Comment by codyloyd** [comment]
@iansowinski thanks for that one... it's a great resource that we've used else where in the curriculum as well.
