### ISSUE TITLE
Weird JS

### ISSUE THREAD

**Issue by colevandersWands** [TheOdinProject/javascript_curriculum#27]
JS is full of wierd quirks.  would you like to have a lesson (sort of a side resource, not central necessarily) that covers some of the primary ones?
type conversion, ...

**Comment by codyloyd** [comment]
might be useful.. yeah

**Comment by colevandersWands** [comment]
tricky things
- https://github.com/jankeLearning/content-md/blob/master/js/01-tricky-things.md

primitives and coercion
- https://github.com/jankeLearning/content-md/blob/master/js/03-primitives.md
