### ISSUE TITLE
are-you-beta-testing-for-us

### ISSUE THREAD

**Issue by colevandersWands** [TheOdinProject/javascript_curriculum#49]
Hey Cody,

Where should people go to beta test the content?  Is it live yet on your website or should they go through this repo? 
I'll be getting some new students soon and I'd like to send them here to get more contribution activity for you.

If you could put links in this are-you-beta-testing and some more specific instructions for following it, that'd be helpful.

I'm also willing to join the new chatroom for testing it if that would help.

Evan

**Comment by codyloyd** [comment]
https://the-odin-project.gitbooks.io/javascript-curriculum/content/

**Comment by colevandersWands** [comment]
got it
