### ISSUE TITLE
Missing Image

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/javascript_curriculum#496]
https://www.theodinproject.com/courses/javascript/lessons/working-with-apis?ref=lnav

There is a missing image under the 'response' section.

![image](https://user-images.githubusercontent.com/4411701/40591613-1f1e9ffc-61da-11e8-9d1c-83462bd5dd4e.png)

**Comment by sarthak-v** [comment]
maybe its time to close this issue (image is there now)
