### ISSUE TITLE
JS101 - DOM manipulation

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/javascript_curriculum#5]
Here's where we introduce putting JS and HTML together.  DOM Manipulation with Javascript.

It could be that this needs to be split into multiple lessons.. that'll depend on how it plays out once we start writing it.

we should 100% definitely stick to PLAIN JS.  Not jQuery.  might even be worth mentioning that this is the type of stuff that many people rely on jQuery for.

concepts to be covered:
1. querySelector (querySelectorAll)
2. classList.add/remove/toggle etc.
3. innerHtml/textContent
4. events/eventListeners
5. appendChild etc.

this would be a _great_ place to include and recommend JS30.. most of those lessons are just simple DOM-manipulation projects with vanilla JS.

should do some simple example project.  Something simple that requires some user interaction like a tip calculator or something (put in the cost and the tip percentage and have it display the amount onscreen)

**Comment by KevinMulhern** [comment]
Potential resource http://domenlightenment.com/

**Comment by codyloyd** [comment]
💯 thanks

**Comment by KevinMulhern** [comment]
This looks like a great series of small tutorials all about the DOM https://www.youtube.com/watch?v=FIORjGvT0kk&list=PL4cUxeGkcC9gfoKa5la9dsdCNpuey2s-V&index=1

**Comment by codyloyd** [comment]
yeah... those do look nice

Good find :D
