### ISSUE TITLE
Gitbooks link sends to legacy gitbooks and returns a 401 error

### ISSUE THREAD

**Issue by troublebob** [TheOdinProject/javascript_curriculum#716]
https://the-odin-project.gitbooks.io/javascript-curriculum/ in the root README sends to a legacy login and when you sign in with your github account it gives this error

![image](https://user-images.githubusercontent.com/1135562/43960733-d6fbce00-9caa-11e8-939a-29c4a07e8e34.png)

**Comment by codyloyd** [comment]
we are no longer using the gitbook.... is there a link to this somewhere we need to remove?

**Comment by troublebob** [comment]
In the README https://github.com/TheOdinProject/javascript_curriculum

**Comment by codyloyd** [comment]
aha
thanks @troublebob 

we used gitbooks extensively when we were testing and writing the curriculum but now that we've published it we're not maintaining the gitbook integration.
