### ISSUE TITLE
test-first-JS

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/javascript_curriculum#8]
a series of javascript exercises that models the format of the test-first ruby stuff and exercism... basically each one is a series of tests that students should make pass one-by-one.

I'm envisioning a pretty lengthy list of them that get broken up and assigned one by one throughout the course.

**Comment by colevandersWands** [comment]
https://github.com/jankeLearning/content-md/blob/master/testing/01-testing-101.md
I've made this about testing.  it doesn't cover testing philosophies, just the basic building blocks of a testing suite
