### ISSUE TITLE
Pages missing 'Next Lesson' button

### ISSUE THREAD

**Issue by plasmadice** [TheOdinProject/javascript_curriculum#80]
Two pages have been found to be lacking the 'Next Lesson' button to go on to the next page.

javascript_curriculum/JS101/fundamentals/fundamentals-5.md
https://www.theodinproject.com/courses/web-development-101/lessons/fundamentals-part-5

&
javascript_curriculum/JS101/final-project.md
https://www.theodinproject.com/courses/web-development-101/lessons/calculator

**Comment by arun1595** [comment]
@plasmadice Thanks for reporting the issue, it has been fixed :)

**Comment by codyloyd** [comment]
Thanks @arun1595
